import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import {
  Zap,
  Sparkles,
  Shield,
  BarChart3,
  ArrowRight,
  CheckCircle2,
  Clock,
  Globe,
} from "lucide-react";

const FEATURES = [
  {
    icon: Zap,
    title: "Lightning Fast",
    description:
      "Generate complete, polished emails in under 2 seconds. No more staring at a blank page.",
  },
  {
    icon: Sparkles,
    title: "Multiple Tones",
    description:
      "Switch between formal, friendly, persuasive, and casual — the right voice for every situation.",
  },
  {
    icon: Shield,
    title: "Privacy First",
    description:
      "Your data stays yours. We never store the content of your generated emails.",
  },
  {
    icon: BarChart3,
    title: "Smart Variations",
    description:
      "Get unique outputs every time — our AI crafts fresh, context-aware emails on demand.",
  },
];

const HOW_IT_WORKS = [
  {
    step: "01",
    title: "Enter your topic",
    description: "Describe what your email is about in a few words or a sentence.",
  },
  {
    step: "02",
    title: "Choose your style",
    description: "Select the tone and length that matches your audience and intent.",
  },
  {
    step: "03",
    title: "Generate & copy",
    description: "Click generate, review your email, and copy it to your clipboard.",
  },
];

const FAQ = [
  {
    question: "How does MailCraft AI generate emails?",
    answer:
      "MailCraft AI uses advanced language models to craft contextually relevant, well-structured emails based on your topic, desired tone, and preferred length.",
  },
  {
    question: "Is there a free plan?",
    answer:
      "Yes! Our Free plan gives you up to 10 email generations per month with access to all tone options. No credit card required.",
  },
  {
    question: "Can I use the generated emails commercially?",
    answer:
      "Absolutely. All content generated by MailCraft AI is yours to use however you like, including for commercial purposes.",
  },
  {
    question: "What languages are supported?",
    answer:
      "MailCraft AI currently works best in English, but can generate emails in other languages when you include the language in your topic description.",
  },
  {
    question: "Is my data secure?",
    answer:
      "Yes. We use industry-standard encryption and never share your data with third parties. Generated email content is not stored after delivery.",
  },
];

export default function HomePage() {
  return (
    <div className="flex flex-col">
      {/* Hero */}
      <section className="relative overflow-hidden bg-gradient-to-b from-background to-muted/30 px-4 py-24 sm:py-32 text-center">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_80%_50%_at_50%_-10%,rgba(0,0,0,0.05),transparent)]" />
        <div className="max-w-4xl mx-auto">
          {/* Badge fades in first */}
          <Badge
            variant="secondary"
            className="mb-6 px-4 py-1.5 text-sm font-medium animate-fade-in"
          >
            ✨ AI-Powered Email Generation
          </Badge>

          {/* Headline slides up with a slight delay */}
          <h1
            className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight text-foreground mb-6 leading-[1.1] animate-fade-in-up animation-delay-100"
          >
            Write perfect emails{" "}
            <span className="text-primary underline decoration-wavy underline-offset-4 decoration-2">
              in seconds
            </span>
          </h1>

          {/* Sub-copy follows */}
          <p
            className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto mb-10 leading-relaxed animate-fade-in-up animation-delay-200"
          >
            Stop spending hours crafting the right words. MailCraft AI generates
            professional, contextual emails for any situation — instantly.
          </p>

          {/* Buttons last in the stagger */}
          <div
            className="flex flex-col sm:flex-row gap-4 justify-center animate-fade-in-up animation-delay-300"
          >
            <Button size="lg" className="text-base px-8 h-12" asChild>
              <Link href="/signup">
                Start for free <ArrowRight className="ml-2 w-4 h-4" />
              </Link>
            </Button>
            <Button size="lg" variant="outline" className="text-base px-8 h-12" asChild>
              <Link href="#how-it-works">See how it works</Link>
            </Button>
          </div>

          <p
            className="text-xs text-muted-foreground mt-6 animate-fade-in animation-delay-400"
          >
            No credit card required · Free plan includes 10 emails/month
          </p>
        </div>
      </section>

      {/* Social proof strip */}
      <section className="border-y border-border bg-muted/20 py-5 px-4">
        <div className="max-w-5xl mx-auto flex flex-wrap justify-center gap-8 text-sm text-muted-foreground">
          {[
            { icon: Clock, text: "Avg. generation time: ~1.2s" },
            { icon: Globe, text: "Used in 30+ countries" },
            { icon: CheckCircle2, text: "1,000+ happy users" },
          ].map(({ icon: Icon, text }) => (
            <div key={text} className="flex items-center gap-2">
              <Icon className="w-4 h-4 text-primary" />
              <span>{text}</span>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section id="how-it-works" className="py-20 px-4 scroll-mt-16">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
              How it works
            </h2>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto">
              Three simple steps to your perfect email.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {HOW_IT_WORKS.map(({ step, title, description }, i) => (
              <div
                key={step}
                className="relative text-center animate-fade-in-up"
                style={{ animationDelay: `${i * 0.12}s` }}
              >
                <div className="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-primary text-primary-foreground text-xl font-bold mb-4">
                  {step}
                </div>
                <h3 className="text-lg font-semibold mb-2">{title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">{description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-20 px-4 bg-muted/20 scroll-mt-16">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
              Everything you need
            </h2>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto">
              Built for professionals, marketers, and anyone who wants to communicate better.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {FEATURES.map(({ icon: Icon, title, description }, i) => (
              <Card
                key={title}
                className="group hover:shadow-md transition-shadow animate-fade-in-up"
                style={{ animationDelay: `${i * 0.1 + 0.05}s` }}
              >
                <CardHeader>
                  <div className="flex items-center gap-3">
                    <div className="flex items-center justify-center w-10 h-10 rounded-xl bg-primary/10 text-primary group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                      <Icon className="w-5 h-5" />
                    </div>
                    <CardTitle className="text-lg">{title}</CardTitle>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground text-sm leading-relaxed">{description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 px-4">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
              Frequently asked questions
            </h2>
            <p className="text-muted-foreground text-lg">
              Everything you need to know about MailCraft AI.
            </p>
          </div>
          <Accordion className="w-full space-y-2">
            {FAQ.map(({ question, answer }, i) => (
              <AccordionItem
                key={i}
                value={`item-${i}`}
                className="border border-border rounded-xl px-6 data-[state=open]:shadow-sm"
              >
                <AccordionTrigger className="text-left font-medium hover:no-underline py-5">
                  {question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground text-sm leading-relaxed pb-5">
                  {answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 px-4 bg-primary text-primary-foreground">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
            Ready to write better emails?
          </h2>
          <p className="text-primary-foreground/80 text-lg mb-10 max-w-xl mx-auto">
            Join thousands of users saving hours every week with AI-powered email generation.
          </p>
          {/* hover-pulse gives a gentle repeating scale on hover */}
          <Button
            size="lg"
            variant="secondary"
            className="text-base px-10 h-12 hover-pulse transition-transform"
            asChild
          >
            <Link href="/signup">
              Get started free <ArrowRight className="ml-2 w-4 h-4" />
            </Link>
          </Button>
        </div>
      </section>
    </div>
  );
}
